# Generated by Django 6.1 on 2026-08-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='qtd_total',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
